### PR TITLE
Allow recursive namespace templating

### LINKED ISSUE #4883: [Core feature] Allow namespaces to be used in task templates
### Motivation: Why do you think this is important?

Currently raw data storage only allows the propeller to provide a single default root S3 location for storing raw data outputs and checkpoints, where normal input/output/error.pb files are stored in a by-namespace key structure.

### Goal: What should the final outcome look like, ideally?

A setting like the following would be a valid storage location that is templated into pod command creations for k8s:
```
    configmap:
      core:
        propeller:
          rawoutput-prefix: "s3://flyte-storage/{{ .Namespace }}"
```

### Describe alternatives you've considered 

Asking all users to specify their `--raw-output-data-prefix` to include the full path to their portion of the bucket that includes their namespace.

###  Propose: Link/Inline OR Additional context 

_No response_

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

### PR DESCRIPTION
**Pull request by neilisaur**
## Tracking issue
_https://github.com/flyteorg/flyte/issues/4883_

Closes #4883

## Why are the changes needed?

Need the ability to automatically split up different projects' raw data storage in a way that identifies the project.

## What changes were proposed in this pull request?

Include the ability to template `{{ .Namespace }}` when rendering the command, specifically templating it last so it can be embedded in prior template replacements, like: `core.propeller.rawoutput-prefix: "s3://flyte-storage/raw-output-data/{{ .Namespace }}"`

## How was this patch tested?

Built and testing locally

## Check all the applicable boxes 

- [x] I updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

### CODE REVIEW

**Review by pingsutw — COMMENTED** [review]
LGTM, could you add a test here? https://github.com/flyteorg/flyte/blob/80a87658fc6f35d2aa0e7b7230497195f564d7ff/flyteplugins/go/tasks/pluginmachinery/core/template/template_test.go#L75

**Comment by neilisaur** [comment]
> LGTM, could you add a test here?
> 
> https://github.com/flyteorg/flyte/blob/80a87658fc6f35d2aa0e7b7230497195f564d7ff/flyteplugins/go/tasks/pluginmachinery/core/template/template_test.go#L75

@pingsutw Absolutely; done!

**Review by pingsutw — APPROVED** [review]
@neilisaur thank you so much

**Review by pingsutw — APPROVED** [review]

**Comment by neilisaur** [comment]
For some reason it was failing on the flyteidl output comparison on some escaped comments. Think my source branch had some weirdness, so reset everything and cherry-picked in changes onto a clean branch for another attempt.

**Comment by neilisaur** [comment]
@pingsutw having trouble here with the Check Go Generate test. It looks like someone updated the comments/checked in generated flyteidl objects that I am not touching in this branch, but the delta check is failing. Is there something I need to do to regenerate the flyteidl on my side to match?

**Comment by neilisaur** [comment]
@pingsutw looks like flyteidl generations had changed under master a few days back. I pulled that in, can I get another set of runs kicked off?

**Review by pingsutw — APPROVED** [review]
LGTM, thank you again @neilisaur

**Pull request merged**
