### PR TITLE
Update Grafana User dashboard

### LINKED ISSUE #5670: [BUG] Flyte user dashboard metric name mismatches
### Describe the bug

The Flyte User dashboard published on [Grafana Marketplace](https://grafana.com/grafana/dashboards/13980-flyte-user-dashboard-via-prometheus/) has the following issues as reported by the community:

- flyte:propeller:all:workflow:accepted - no data
- flyte:propeller:all:workflow:success_duration_ms_count - needed to be flyte:propeller:all:workflow:event_recording:success_duration_ms_count
- flyte:propeller:all:workflow:failure_duration_ms_count - no data. I'm able to visualise failed tasks instead of workflows using flyte:propeller:all:task:event_recording:failure_duration_ms_count
- flyte:propeller:all:workflow:workflow_aborted - no data
- success/failure/queueing time by quantile, and User VS System errors - no data unless I use the 'unlabeled_ms' version of the metrics, which doesn't allow us to filter by project/domain/workflow
- CPU/Memory limits VS quota - no 'kube_resourcequota' metric found in our prometheus setup, but maybe this is unique to our setup. I was able to more-or-less recreate these visualisations using our own cluster prometheus metrics
- Pending tasks - not clear if this works, only one data point visualised (but we've been testing across multiple workflows)
CPU/Memory Usage Percentage - infinite loading

### Expected behavior

The dashboards should not only work OOB but should be better documented in terms of metric explanations and expected behavior.
The published dashboards should reflect those updates

### Additional context to reproduce

_No response_

### Screenshots

_No response_

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

### PR DESCRIPTION
**Pull request by davidmirror-ops**
Closes #5670

## Why are the changes needed?

The user dashboard currently published on Grafana marketplace uses outdated metric names and undocumented dependencies.

## What changes were proposed in this pull request?

This PR updates metric names and changes some panel graph types from `TimeSeries` to `BarGauge` to better render `by (quantile)` queries. 
Also, it deprecates the use of `label_execution_id` to mitigate high-cardinality scenarios.

## How was this patch tested?

Installed on a Grafana instance provided by the `kube-prometheus-stack` Helm chart, pointing to a `flyte-core` cluster with `ServiceMonitor` enabled.

image

### Setup process
1. Installed the `kube-prometheus-stack` using the [Helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/) making sure the following block is added to the values file:

```
kube-state-metrics:
  metricLabelsAllowlist:
    - pods=[node-id,workflow-name,task-name]
```

Without it, those 3 labels won't be available and they are used for filtering on multiple metrics.
2. Configured `flyte-core` with the following sections as part of the values file:
```
flyteadmin:
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack #this is particular to the kube-prometheus-stack
  selectorLabels:
    - app.kubernetes.io/instance: flyte-coretf #this is typically the name of the Helm release
    - app.kubernetes.io/name: flyteadmin
flytepropeller:
  service:
    enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
  selectorLabels:
    - app.kubernetes.io/instance: flyte-coretf #Helm release name
    - app.kubernetes.io/name: flytepropeller 
```

3. Import the contents from `flyteuser-dashboard.json`  into Grafana

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Docs link

Once this is approved, I can proceed to upload the updated dashboard to Grafana Marketplace, updating the docs (including the link to the marketplace content)

### CODE REVIEW

**Comment by charliemoriarty** [comment]
Thanks for working on these updates!

This is already looking a lot better - success metrics are working well, though we still see a few small issues on the imported dashboard:
- failed workflows aren't shown even though we did observe failures in this time period. I believe the stats for these workflows are being recorded against `failure_duration_unlabeled_ms_count ` instead of `failure_duration_ms_count`
- failed workflow execution time is showing in the order of weeks - this might need a unit of `milliseconds` instead of `seconds`
- the three panels in the task stats group all show an error: "many-to-many matching not allowed: matching labels must be unique on one side"

Screenshot 2024-09-13 at 10 38 08

**Comment by davidmirror-ops** [comment]
@charliemoriarty thanks so much for reporting.
I'm still exploring the Failed Workflows panel as it uses the `flyte:propeller:all:workflow:event_recording:failure_duration_ms_count` and it works when I test it standalone but for some reason is not displayed correctly. 
Also I'll see why are you getting that error on Task stats, it works on my flyte-binary environment:

image

I forgot to mention that with `kube-state-metrics` v2.0.0  or higher, you have to enable the required labels for this to work. If you're using the Helm chart it's a matter of upgrading with a values file including:

```
kube-state-metrics:
  metricLabelsAllowlist:
    - pods=[node-id,workflow-name,task-name]
```
Once I have updates on this, will push them here for you to test. 

Thanks!

**Comment by davidmirror-ops** [comment]
@charliemoriarty I'm curious how this dashboard looks in your environment after recent changes.

**Comment by Tom-Newton** [comment]
Thanks for updating this. It looks good to me but I haven't looked particularly carefully. The updates I made were mostly focused on the admin and propeller dashboards so don't worry about stepping on my changes.

**Comment by charliemoriarty** [comment]
> @charliemoriarty I'm curious how this dashboard looks in your environment after recent changes.

@davidmirror-ops Thanks again for the work on this! Apologies for the very, very late reply - somehow I missed the notification for the thread at the time 🤦  I can confirm that these changes look a lot better, and that failure visualisation is working as expected. The updates to the documentation are really helpful as well - I think we are missing the `metricLabelsAllowList` which is why the task visualisations weren't working as expected. Hopefully this helps others get set up out of the box!

**Pull request merged**
