### PR TITLE
Fixing cache overwrite metadata update

### PR DESCRIPTION
**Pull request by hamersaw**
## Tracking issue
Iterating on PR - https://github.com/flyteorg/flyte/pull/4550

## Why are the changes needed?
Refer to linked PR

## What changes were proposed in this pull request?
Refer to linked PR

## How was this patch tested?
Refer to linked PR

### Setup process
Refer to linked PR

### Screenshots
Refer to linked PR

## Check all the applicable boxes 

- [x] I updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Related PRs
https://github.com/flyteorg/flyte/pull/4550

## Docs link
Refer to linked PR

### CODE REVIEW

**Comment by pvditt** [comment]
@hamersaw 

Did this work on your machine? The changes look fine but I'm not able to trace any calls to UpdateArtifact aside from the uncalled [Update](https://github.com/flyteorg/flyte/blob/14915dcb1cbde884c6b8d514114dc48cf1342fbf/flytepropeller/pkg/controller/nodes/catalog/datacatalog/datacatalog.go#L337) from propellor to persist the updates.

**Review by pvditt — COMMENTED** [review]
@hamersaw

Did this work on your machine? The changes look fine but I'm not able to trace any calls to UpdateArtifact aside from the uncalled [Update](https://github.com/flyteorg/flyte/blob/14915dcb1cbde884c6b8d514114dc48cf1342fbf/flytepropeller/pkg/controller/nodes/catalog/datacatalog/datacatalog.go#L337) from propellor to persist the updates.

**Comment by hamersaw** [comment]
> @hamersaw
> 
> Did this work on your machine? The changes look fine but I'm not able to trace any calls to UpdateArtifact aside from the uncalled [Update](https://github.com/flyteorg/flyte/blob/14915dcb1cbde884c6b8d514114dc48cf1342fbf/flytepropeller/pkg/controller/nodes/catalog/datacatalog/datacatalog.go#L337) from propellor to persist the updates.

Great catch! I am seeing the exact same issue, thanks for keeping me honest. Will trace this down.

**Comment by hamersaw** [comment]
@pvditt Seems I ported this over incorrectly on the [fast cache](https://github.com/flyteorg/flytepropeller/pull/485)
 work. In the [original PR](https://github.com/flyteorg/flytepropeller/pull/489) that added the cache overwrite functionality we automatically call `Update` when [cache overwrite is set](https://github.com/blackshark-ai/flytepropeller/blob/7edfbfe0c7fdb57a608bedb32750b8a14c0f88ea/pkg/controller/nodes/task/pre_post_execution.go#L225-L231). Internally, this creates the dataset if it doesn't exist. So I added this same logic here, performed local testing of all the scenarios I could think of, and I think this is correct now. Please take a look.

**Review by pvditt — APPROVED** [review]

**Comment by ysysys3074** [comment]
> @pvditt Seems I ported this over incorrectly on the [fast cache](https://github.com/flyteorg/flytepropeller/pull/485) work. In the [original PR](https://github.com/flyteorg/flytepropeller/pull/489) that added the cache overwrite functionality we automatically call `Update` when [cache overwrite is set](https://github.com/blackshark-ai/flytepropeller/blob/7edfbfe0c7fdb57a608bedb32750b8a14c0f88ea/pkg/controller/nodes/task/pre_post_execution.go#L225-L231). Internally, this creates the dataset if it doesn't exist. So I added this same logic here, performed local testing of all the scenarios I could think of, and I think this is correct now. Please take a look.

hi sorry for delay regarding the PR and thanks for iterating on my earlier PR. And i just noticed in my company's internal repo, we still have `pre_post_executor.go` which calls `Update` method in propeller when overwrite cache is on, but it seems open source repo have removed that file and added `cache.go` instead. thanks for the fix here!

**Pull request merged**
