### PR TITLE
Allow passing cluster pool to run-tests.py

### PR DESCRIPTION
**Pull request by iaroslav-ciupin**
## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] All commits are signed-off.

### CODE REVIEW

**Comment by squiishyy** [comment]
I think for now we want to make these changes in the flyte/boilerplate repo? [This ticket ](https://github.com/flyteorg/flyte/issues/4281)is tracking work to migrate towards having this being managed out of the flyte monorepo but i dont think it's done yet. @eapolinario is that right?

**Comment by squiishyy** [comment]
Here's my PR from the boilerplate repo for ref! https://github.com/flyteorg/boilerplate/pull/89

**Comment by iaroslav-ciupin** [comment]
@squiishyy  https://github.com/flyteorg/boilerplate/pull/90

**Review by pingsutw — DISMISSED** [review]

**Comment by iaroslav-ciupin** [comment]
change was already merged to master

**Pull request closed without merging**
