### PR TITLE
Fix broken Kustomize link in docs

### PR DESCRIPTION
**Pull request by orf**

### CODE REVIEW

**Review by kumare3 — DISMISSED** [review]

**Comment by kumare3** [comment]
@orf can you please sign-off on the DCO. Here is a contributing guide docs - https://docs.flyte.org/en/latest/community/contribute.html#code

**Comment by orf** [comment]
I’ll need to do this tomorrow, but sure. I created this through the web UI which is quite convenient for these kind of changes - you might want to consider relaxing the DCO requirement for one-line doc fixes if possible.

**Comment by kumare3** [comment]
@orf I know, but this is not us - it is Linux Foundations' requirements. As Flyte is part of the Linux Foundation AI And data projects. But I think there is a chrome extension for doing this through the UI - https://chrome.google.com/webstore/detail/dco-github-ui/onhgmjhnaeipfgacbglaphlmllkpoijo?hl=en

**Comment by orf** [comment]
Fair enough! I've fixed it 👍

**Pull request merged**
