### PR TITLE
Add SYS_PTRACE setting to Co-pilot container config.

### PR DESCRIPTION
**Pull request by dylanspag-lmco**
## Tracking issue

Related to #5462

## Why are the changes needed?

The issue https://github.com/flyteorg/flyte/issues/5462 describes the problem in detail.

## What changes were proposed in this pull request?

I made `SYS_PTRACE` an optional setting for co-pilot containers.

## How was this patch tested?

I added the default setting to the "happy" and "happy stow backend" Co-pilot Container tests. I also added a test to ensure the SYS_PTRACE capability is present when the setting is enabled.

## Check all the applicable boxes

- [x] I updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Related PRs

See #5556.

### CODE REVIEW

**Comment by neverett** [comment]
Pinging @davidmirror-ops for deployment docs changes.

**Comment by davidmirror-ops** [comment]
@dylanspag-lmco Thank you for contributing! I was wondering if this wouldn't be a breaking change once released? Shouldn't we default to opt-out?

**Comment by dylanspag-lmco** [comment]
@davidmirror-ops I'm not sure of all of the downstream implications. The conversation in #5462 seemed to indicate removing it might be relatively low impact, which is why I had set the default as opt-in. Which would you prefer?

**Comment by davidmirror-ops** [comment]
@dylanspag-lmco I think the goal is to make it configurable as opposed to hardcoded. Disabling it by default may break functionality for current users.

**Comment by dylanspag-lmco** [comment]
@davidmirror-ops makes sense. I just swapped the default behavior and updated the tests accordingly.

**Comment by davidmirror-ops** [comment]
@dylanspag-lmco thanks so much for your effort so far. I've been talking to other maintainers about this change and we think the best path forward is to no accept it as it would break `RawContainer` functionality, the only instance where the copilot container is used in Flyte.
Flyte needs a way to determine that the user code finished execution and to capture the outcome (Success/Failure) and three mechanisms were envisioned to achieve that goal as described in the [original flytecopilot design](https://github.com/flyteorg/flyte/tree/master/flytecopilot#raw-notes)

1. Poll the kube-api: it would require less process on the user code but a deeper investigation/benchmarking to determine the sane defaults to configure the kube-client and avoid overloading the kube-api server. Recent testing showed that this won't work, and it would require to spend time updating [the code](https://github.com/flyteorg/flyte/blob/master/flytecopilot/cmd/containerwatcher/kubeapi_watcher.go).
2. [Implement a file-based protocol](https://github.com/flyteorg/flyte/blob/master/flytecopilot/cmd/containerwatcher/file_watcher.go). With this option, the user code had to include logic to drop the outputs to a certain directory and make the User code use a FileWatcher to determine the result of its own execution. Depending on the outcome (SUCCESS/FAILURE) it would need to write a different file, all of that before returning. Recent testing shows that it works butthere are potential performance implications going this route.Also, there is now wat to inspect that user code ran, just waiting for a file to drop.

Notice that for the two options above there is no way to activate them or select them, no flag.

4. Share process namespace between copilot and the user code container (current default). With this mechanism, the copilot container downloads the inputs, watches the user code container for a result (using the shared process namespace and, hence, requiring the `SYS_PTRACE` capability), and copies the outputs, or updates flyteadmin,  depending on whether the task succeeded or failed, respectively.

Considering this context, we cannot make `SYS_PTRACE` configurable because then we'd also have to disable `RawContainer`, and also there is no flag today to do so.
The closest acceptable change would be about creating that flag and exposing it on the Helm chart. 

I hope the above explanation help in some way, and please let us know how we can help you with your current use case.

**Comment by dylanspag-lmco** [comment]
@davidmirror-ops Thank you for explanation. I'll consult with my organization's flyte admins to see if there's anything we can do internally to get ContainerTasks working without disabling this.

**Comment by vlibov** [comment]
> Considering this context, we cannot make `SYS_PTRACE` configurable because then we'd also have to disable `RawContainer`, and also there is no flag today to do so. The closest acceptable change would be about creating that flag and exposing it on the Helm chart.
> 

What is the principal difference between the proposed changes in this PR and "exposing on the Helm chart"?
Thanks!

**Pull request closed without merging**
