### PR TITLE
Enable agent service by default

### PR DESCRIPTION
**Pull request by pingsutw**
## Tracking issue
https://github.com/flyteorg/flyte/issues/3936

## What changes were proposed in this pull request?
Note: This PR only enables the agent-service plugin by default in the helm chart and won't deploy an agent server.
The reason to do that because people won't need to modify the propeller configmap after they install the agent (`helm install flyteagent ...`), and also give people with more visibility into flyte agent.

## How was this patch tested?
Local sandbox

## Check all the applicable boxes 

- [x] I updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Related PRs
NA

## Docs link
NA

### CODE REVIEW

**Review by Future-Outlier — DISMISSED** [review]
LGTM, thank you

**Review by EngHabu — DISMISSED** [review]
What happens if you try to use an agent that isn't deployed now?

**Review by Future-Outlier — APPROVED** [review]
LGTM, thank you

**Comment by Future-Outlier** [comment]
> What happens if you try to use an agent that isn't deployed now?

flytepropeller will send error to flyteadmin, and flyteadmin will send error message to flyteconsole.
We will have a watcher to dynamically check avaialbe agent deployments and update to flytepropeller.

**Pull request merged**
