### PR TITLE
Copy user guide to flyte repo

### PR DESCRIPTION
**Pull request by ppiegaze**
Copy user guide content from flytesnacks to flyte
No changes to content or structure of docs website

### CODE REVIEW

**Review by neverett — APPROVED** [review]
LGTM although noting that this will change the URL structure for the user guide pages, so we may need to put redirects in place.

**Review by pingsutw — APPROVED** [review]

**Comment by pingsutw** [comment]
@neverett @ppiegaze we can merge it, right?

**Comment by neverett** [comment]
> @neverett @ppiegaze we can merge it, right?

I think we should hold off merging for the moment -- the plan is for Peeter to take a pass at updating old docs links in the Flyte repo first, then we can merge this PR, then he'll update links again, since this PR will change the URL structure for some docs pages. @ppiegaze can confirm, though.

**Comment by pingsutw** [comment]
gotcha, thanks

**Comment by ppiegaze** [comment]
Let's wait to merge this until I can add the link fixes as well. Unfortunately that will be late next week as I am off for a few days

**Comment by pingsutw** [comment]
no rush; just let me know if there is anything I can help with.

**Comment by ppiegaze** [comment]
@neverett All the link updates have been done. We can merge this now, on your approval

**Review by neverett — APPROVED** [review]

**Pull request merged**
