### PR TITLE
DOC-252 Fix broken mermaid diagrams in docs

### PR DESCRIPTION
**Pull request by neverett**
## Why are the changes needed?

Closes https://github.com/flyteorg/flyte/issues/4864

## What changes were proposed in this pull request?

* Update mermaid diagram format in conf.py
* Install Node.js and `npm install -g @mermaid-js/mermaid-cli` during build process

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] All commits are signed-off.

## Related PRs

https://github.com/flyteorg/flyte/pull/5373

## Docs link

TK

### CODE REVIEW

**Review by davidmirror-ops — APPROVED** [review]
Thank you!

**Comment by neverett** [comment]
@davidmirror-ops looks like docs tests are failing because the MMCloud plugin example page has a 404ing link.  [Here's a PR](https://github.com/flyteorg/flyte/pull/5468) to remove and redirect the MMCloud plugin pages -- once it's merged, I can update the branch in this PR and the tests should pass.

**Comment by neverett** [comment]
@cosmicBboy I'm able to generate mermaid diagrams locally with the changes in this PR, but [docs tests](https://github.com/flyteorg/flyte/actions/runs/9473230997/job/26100375556?pr=5467) are failing with `command '/home/docs/.asdf/shims/mmdc' cannot be run (needed for mermaid output), check the mermaid_cmd setting`. 

That is the location `mmdc` ends up installed in on the build server, so I'm not sure what else to try -- any ideas?

**Comment by cosmicBboy** [comment]
As far I as I can tell the `mmdc` path will be different in readthedocs build env from the githin actions monodocs env.

I think the monodocs build GH workflow needs to be updated: https://github.com/flyteorg/flyte/blob/c10346d5bc07e37783c277f6d3bede301ae3ad99/flytectl/.github/workflows/monodocs_build.yml#L2

And then in `conf.py` the path needs to be set as an environment variable.

However, weird thing is that even in the readthedocs preview the mermaid diagrams aren't showing up: https://flyte--5467.org.readthedocs.build/en/5467/deployment/configuration/auth_appendix.html

**Comment by cosmicBboy** [comment]
trying out this smaller configuration change: https://github.com/flyteorg/flyte/pull/5498

**Comment by neverett** [comment]
Closing since this was fixed in https://github.com/flyteorg/flyte/pull/5498

**Pull request closed without merging**
