### PR TITLE
Fix indentation in datacatalog deployment template

### PR DESCRIPTION
**Pull request by sbrunk**

### CODE REVIEW

**Comment by kumare3** [comment]
Cc @evalsocket @EngHabu

**Review by EngHabu — APPROVED** [review]

**Comment by sbrunk** [comment]
I'm not sure why the diff check fails on the README files.
```
files different: charts/flyte-core/README.md
charts/flyte/README.md
```
I ran `make helm` locally using helm 3.6.3

**Comment by wild-endeavor** [comment]
i committed some changes so now i'm breaking you.   but also running helm locally on my mac with 3.6.3 does result in some differences too.  not sure what's going on.

```
ytong@argus:~/dev/flyte [arn:aws:eks:us-east-2:590375264460:cluster/flyte-demo-2] (wpr/1495) $ helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

**Comment by sbrunk** [comment]
Ok @wild-endeavor I just rebased against master to resolve the conflicts but the diff error still occurs of course.

**Comment by wild-endeavor** [comment]
can you give me write access to  your fork?  i can push a commit

**Comment by sbrunk** [comment]
Uh I didn't realize that I had pushed that to my fork instead of here. You should have access now @wild-endeavor

**Review by wild-endeavor — APPROVED** [review]

**Comment by sbrunk** [comment]
Looks better now. I wonder why running `make helm` produces a different result on my linux machine.

**Pull request merged**
