### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by pingsutw**
Fix broken links

### CODE REVIEW

**Comment by samhita-alla** [comment]
@pingsutw, can you take a look at the failed check?

**Comment by pingsutw** [comment]
@samhita-alla I'm not familiar with sphinx. Do you know how to fix it? 
```
/Users/kevin/git/flyte/rsts/concepts/tasks.rst:117:undefined label: cookbook:sphx_glr_auto_examples_basics_files.py
```

**Comment by Yicheng-Lu-llll** [comment]
Maybe this comment can help: https://github.com/flyteorg/flytesnacks/pull/1011#issuecomment-1616055709.

**Comment by pingsutw** [comment]
@samhita-alla fixed it

**Review by samhita-alla — APPROVED** [review]
Thanks, @pingsutw!

**Pull request merged**
