### PR TITLE
beacuse flyte-binary image has no version tag, it is replaced with fl…

### PR DESCRIPTION
**Pull request by sorushsaghari**
## Tracking issue
Related to the discussion in Slack about the naming of the Flyte Docker image tag.

## Why are the changes needed?
The current Docker image `flyte-binary` does not have a stable version tag, which leads to confusion during deployments. To prevent this, the image name is being changed to `flyte-binary-release`, as agreed upon in the discussion.

## What changes were proposed in this pull request?
This PR proposes changing the Docker image name from `flyte-binary` to `flyte-binary-release` in the Flyte Helm chart. This change ensures that a stable version tag is consistently used, reducing confusion and aligning with the team's agreed standards.

### Changes:
- Updated the Flyte Helm chart to use `cr.flyte.org/flyteorg/flyte-binary-release` as the image repository.
- Set the image tag to `latest` and the pull policy to `IfNotPresent`.

## How was this patch tested?
The changes were verified through updates to the Flyte Helm chart configuration. Further testing includes:
- Deployment testing with the updated Helm chart to ensure the correct image is pulled.
- Validation of the stable tag behavior by deploying the Helm chart with the new `flyte-binary-release` image.

### Setup process
1. Updated the Helm chart configuration with the new image repository and tag.
2. Deployed the updated Helm chart to a test environment.
3. Verified the deployment success and checked the pulled image version.

### Screenshots
N/A

## Check all the applicable boxes
- [x] I updated the Helm chart accordingly.
- [ ] All new and existing tests passed.
- [ ] All commits are signed-off.

## Related PRs
None

### CODE REVIEW

**Comment by sorushsaghari** [comment]
@davidmirror-ops can you help me with the failed tests?

**Comment by davidmirror-ops** [comment]
@sorushsaghari sure! please run `make helm` from your fork, and push the changes

**Comment by sorushsaghari** [comment]
> @sorushsaghari sure! please run `make helm` from your fork, and push the changes

after the  make helm i heve some merge conflicts

**Comment by sorushsaghari** [comment]
@davidmirror-ops could you please help me with this. i fixed the conflicts

**Comment by sorushsaghari** [comment]
@eapolinario can you pls merge it ? it is taking so much time and, again i have some conflicts

**Comment by eapolinario** [comment]
Unfortunately, this is not the correct fix to version the `flyte-binary` image. I opened https://github.com/flyteorg/flyte/pull/6010 with the proper fix.

**Pull request closed without merging**
