### PR TITLE
Additional guide for configuring GKE to support GPU tasks

### PR DESCRIPTION
**Pull request by ChickenTarm**
## Describe your changes

Added a section describing how to set up the GKE cluster to allow GPU tasks. This would make life easier for first time flyte users who are trying to do this for the first time. Making this manual a one stop shop in steps and information would be ideal.

## Check all the applicable boxes 

- [ x] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] All commits are signed-off.

### CODE REVIEW

**Comment by ChickenTarm** [comment]
I think it would be good to have the accompanying gcloud command, but I actually don't know them. I did it via the dashboard.

**Comment by wild-endeavor** [comment]
Thank you for the detailed instructions!  We're in the process of revamping the deployment documentation structure.  Please bear with us while we try to figure out where this information should go.

**Comment by wild-endeavor** [comment]
@ChickenTarm - would you be able to create a discussion with this content on https://github.com/flyteorg/flyte/discussions/categories/deployment-tips-tricks instead please?  We think that will make for a better forum.

Thank you.

**Comment by davidmirror-ops** [comment]
the process is now covered in the docs with examples for GKE: https://docs.flyte.org/en/latest/user_guide/productionizing/configuring_access_to_gpus.html

**Pull request closed without merging**
