### PR TITLE
[Docs]  docs cleanup

### PR DESCRIPTION
**Pull request by idivyanshbansal**
Signed-off-by: Divyansh Bansal <divyansh.bansal25@gmail.com>

If this change did not fulfill your needs please comment for any changes or close this request. It is really depressing for me to get spam.

### CODE REVIEW

**Comment by evalsocket** [comment]
@idivyanshbansal You made changes in flyte repo but the issue is related to [flytectl](https://github.com/flyteorg/flytectl).

**Comment by idivyanshbansal** [comment]
> @idivyanshbansal You made changes in flyte repo but the issue is related to [flytectl](https://github.com/flyteorg/flytectl).

@evalsocket So Sorry Sir 😅. Sir if you find my changes useful to your repository then please check them out or just message me to close my request.

**Comment by samhita-alla** [comment]
Thank you for creating the PR, @idivyanshbansal. We don't really need these changes, hence closing it. If you'd like to work on any additional issues, refer to our [hacktoberfest-tagged issues](https://github.com/flyteorg/flyte/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest).

**Comment by idivyanshbansal** [comment]
> Thank you for creating the PR, @idivyanshbansal. We don't really need these changes, hence closing it. If you'd like to work on any additional issues, refer to our [hacktoberfest-tagged issues](https://github.com/flyteorg/flyte/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest).

No problem @samhita-alla. Have a nice day. 😄

**Pull request closed without merging**
