### PR TITLE
Fix pip-compile errors when building (doc-)requirements.txt

### PR DESCRIPTION
**Pull request by ByronHsu**
## Tracking issue

I am unable to generate `doc-requirements.txt` due to the following errors. Using backtracking resolver can solve this issue.
Also, it seems that legacy resolver will be deprecated and replaced by backtracking resolver after `7.0.0`, which is the recommended way.

```
$ python --version
Python 3.9.5

$ make doc-requirements.txt
...
WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.
...
Using legacy resolver. Consider using backtracking resolver with `--resolver=backtracking`.
Could not find a version that matches docutils<0.18,>=0.14,~=0.18.0 (from sphinx==4.5.0->-r doc-requirements.in (line 2))
Tried: 0.3, 0.3.5, 0.3.7, 0.3.9, 0.4, 0.5, 0.6, 0.7, 0.8, 0.8.1, 0.9, 0.9.1, 0.10, 0.11, 0.12, 0.12, 0.13.1, 0.13.1, 0.14, 0.14, 0.15, 0.15, 0.15.1.post1, 0.15.2, 0.15.2, 0.16, 0.16, 0.17, 0.17, 0.17.1, 0.17.1, 0.18, 0.18, 0.18.1, 0.18.1, 0.19, 0.19
Skipped pre-versions: 0.14rc1, 0.14rc2, 0.16b0.dev0, 0.16b0.dev0, 0.16rc1, 0.16rc1, 0.17b1, 0.17b1, 0.17.1b1.dev0, 0.17.1b1.dev0, 0.18b1, 0.18b1, 0.18.1b0, 0.18.1b0, 0.19b1, 0.19b1
There are incompatible versions in the resolved dependencies:
  docutils (from sphinx-panels==0.6.0->-r doc-requirements.in (line 10))
  docutils<0.18,>=0.14 (from sphinx==4.5.0->-r doc-requirements.in (line 2))
  docutils~=0.18.0 (from sphinx-tabs==3.4.1->-r doc-requirements.in (line 14))
make: *** [doc-requirements.txt] Error 2
```

## Describe your changes

Add `--resolver=backtracking` to `pip-compile`

## Check all the applicable boxes 

- [x] I updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Tests

```
$ make doc-requirements.txt
...
sphinxcontrib-yt==0.2.2
    # via -r doc-requirements.in
sphinxext-remoteliteralinclude==0.4.0
    # via -r doc-requirements.in
typing-extensions==4.4.0
    # via astroid
unidecode==1.3.6
    # via sphinx-autoapi
urllib3==1.26.14
    # via requests
virtualenv==20.17.1
    # via pre-commit
wrapt==1.14.1
    # via astroid
zipp==3.12.0
    # via importlib-metadata

# The following packages are considered to be unsafe in a requirements file:
# setuptools
```

## Note to reviewers

I am using this os. Not sure if other platforms get the same behavior. Please help test on others! 
image

### CODE REVIEW

**Comment by ByronHsu** [comment]
@EngHabu @kumare3 Can you help review? Thanks!

**Comment by kumare3** [comment]
@ByronHsu thank you. I will also add you to the core contributors

**Review by EngHabu — APPROVED** [review]
Thank you!

**Comment by ByronHsu** [comment]
@kumare3 It is my honor. Thanks!!

**Pull request merged**
