### PR TITLE
[flyteadmin] Use WithContext in all DB calls

### PR DESCRIPTION
**Pull request by Sovietaced**
I have been working in the DB code to implement some RBAC and I noticed some TODOs about using `db.WithContext`. I audited the code and added `db.WithContext` for any missing DB methods. This should ensure that all DB calls support distributed tracing.

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

### CODE REVIEW

**Comment by katrogan** [comment]
thank you for this! do you need any help preparing this PR to move it from draft and ready for review?

**Comment by Sovietaced** [comment]
> thank you for this! do you need any help preparing this PR to move it from draft and ready for review?

I was going to wait for CI to run but it looks like it has now so feel free to review.

**Comment by katrogan** [comment]
great, thank you! re-running the timed-out test now

re:
>  DB code to implement some RBAC
I'd be curious if you could share what RBAC work you're doing?

**Review by katrogan — APPROVED** [review]

**Comment by Sovietaced** [comment]
> I'd be curious if you could share what RBAC work you're doing?

I added RBAC to our fork so that we can restrict API access as well do project/domain level resource filtering/isolation. The filtering is most elegantly done at the data layer so that pagination works nicely.

**Comment by katrogan** [comment]
neat thanks for sharing! how are you mapping user identity to permitted projects and domains (also happy to continue this conversation on OSS slack if you're around)

**Pull request merged**
