### PR TITLE
Grafana dashboard updates

### PR DESCRIPTION
**Pull request by Tom-Newton**
## Why are the changes needed?
There are a few issues with the dashboards as is. This includes some bugs and some outdated metric names. 

## What changes were proposed in this pull request?
- This is a series of incremental changes I ended up making when trying to understand flyte propeller performance and debug a problem on our network. 
  - Add a few extra graphs/shuffle some around a bit. 
  - Fix some aggregation bugs e.g. missing `rate` funciton while the title says rate
  - Fix some axis labels. 
  - Correct some metrics names based on flyte-core 1.11
  - Add a few descriptions. 
- Probably this is still a long way from perfect but I think its probably still worth contributing. 

### Screenshots
image
image

## Check all the applicable boxes 

- [x] I updated the documentation accordingly. Not applicable 
- [x] All new and existing tests passed. Not applicable
- [x] All commits are signed-off.

### CODE REVIEW

**Comment by Tom-Newton** [comment]
It looks like the CI failure is because matplotlib's website is down and breaking a docs build.

**Review by davidmirror-ops — APPROVED** [review]
Thank you!

**Comment by davidmirror-ops** [comment]
@neverett any idea why CI fails with a doc that's not changed by this PR?

**Comment by Tom-Newton** [comment]
Actually that looks like a different error now

**Comment by neverett** [comment]
@Tom-Newton @davidmirror-ops I think you may need to merge master in to pick up changes from https://github.com/flyteorg/flyte/pull/5254 since that introduced some significant updates to the docs build

**Comment by Tom-Newton** [comment]
Sorry for being so slow. I just rebased on `master` :crossed_fingers:

**Pull request merged**
