### PR TITLE
Use Latest FlyteIDL for MonoDoc CI

### PR DESCRIPTION
**Pull request by Future-Outlier**
### Problem
Currently, the latest flytekit and the latest flyteidl (beta version) are released.
I want to update the version in monodoc so that some PR used the latest flyteidl can be merged.
### Solution
1. update the dependency in `monodocs-environment.yaml`
2. use `conda-lock -f monodocs-environment.yaml --lockfile monodocs-environment.lock.yaml` to update dependencies.

### CODE REVIEW

**Comment by Future-Outlier** [comment]
@pingsutw Please help merge it, thanks!

**Comment by Future-Outlier** [comment]
@cosmicBboy if possible, please take a look, thank you very much!

**Comment by Future-Outlier** [comment]
error message:

Locking dependencies for ['linux-64', 'osx-arm64']...
INFO:conda_lock.conda_solver:linux-64 using specs ['python 3.9.*', 'pip *', 'codespell', 'furo', 'gitpython', 'ipython !=8.7.0', 'graphviz', 'jupytext', 'myst-nb', 'psycopg2-binary', 'recommonmark', 'sphinx 4.5.0', 'sphinx-prompt', 'sphinx-click', 'sphinx-autoapi', 'sphinx-copybutton', 'sphinx-issues', 'sphinx_fontawesome', 'sphinx-panels', 'sphinxcontrib-mermaid', 'sphinxcontrib-youtube 1.2.0', 'sphinx-tabs', 'sphinx-tags 0.2.1', 'retry', 'botocore', 'fsspec', 'google-cloud-bigquery', 'markdown', 'plotly', 'great-expectations', 'datasets', 'kubernetes', 'modin', 'pandera', 'pydantic', 'papermill', 'jupyter', 'polars', 'pyspark', 'sqlalchemy', 'pytorch', 'skl2onnx', 'numpy 1.23.5', 'tf2onnx', 'tensorflow >=2.13.0', 'scikit-learn', 'dask', 'mlflow 2.7.0', 'snowflake-connector-python', 'vaex-core']

**Comment by eapolinario** [comment]
subsumed by https://github.com/flyteorg/flyte/pull/4815

**Pull request closed without merging**
