### PR TITLE
Housekeeping API version ClusterRoleBinding #1272

### PR DESCRIPTION
**Pull request by askalik**
Updating rbac.authorization.k8s.io/v1beta1 to rbac.authorization.k8s.io/v1 as rbac.authorization.k8s.io/v1beta1 is deprecated

Resolves issue #1272

### CODE REVIEW

**Comment by askalik** [comment]
@brucearctor not sure if it would be you that would review this,  but this is ready for review

**Comment by kumare3** [comment]
@askalik it will be @EngHabu and @evalsocket

**Comment by EngHabu** [comment]
Mind cleaning up the PR? I think it needs a rebase

**Comment by EngHabu** [comment]
The PR seems abandoned... please reopen and clean up if not...

**Pull request closed without merging**
