### PR TITLE
[copilot] rename sidecar to uploader

### PR DESCRIPTION
**Pull request by wayner0628**
## Tracking issue

https://github.com/flyteorg/flyte/issues/5995
## Why are the changes needed?

The current naming of the upload container in Copilot as `sidecar` can be confusing, especially since we also have a dedicated `downloader` container. Given that this container primarily handles upload tasks, renaming it to something more descriptive would improve readability and understanding of its role.
## What changes were proposed in this pull request?

~~Replace all occurences of `sidecar` with `uploader`.~~
Simply change the string value [here](https://github.com/flyteorg/flyte/blob/b3330ba4430538f91ae9fc7d868a29a2e96db8bd/flyteplugins/go/tasks/pluginmachinery/flytek8s/copilot.go#L23), suggested by @eapolinario (thank you), because replacing all occurences will introduce too many changes across the codebase.
Also, for flyte users, they will only see the name of container.
### Screenshots
- k8s
Screenshot 2024-11-21 at 11 18 20 AM
- unit test
Screenshot 2024-11-25 at 9 48 33 PM

## Check all the applicable boxes 

- [x] I updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

### CODE REVIEW

**Review by eapolinario — COMMENTED** [review]
Thank you. Can you add a test to `copilot_test.go` to verify the container name change?

**Comment by wayner0628** [comment]
@eapolinario test added, thank you!

**Review by Future-Outlier — COMMENTED** [review]
thank you

**Review by Future-Outlier — APPROVED** [review]
thank you

**Pull request merged**
