### PR TITLE
[fix] #3919 : Added Output Format Option to flyte single start Command

### LINKED ISSUE #3919: [FlyteCTL Feature] add a --output flag for pyflyte register
### Describe the feature/command for FlyteCTL

pyflyte register today does not have any mechanism for providing an organized output containing the registered workflow/task/launchplan names, and their versions.

This request would be to provide a --output=X flag that can denote how the output should be formatted.
This could be by default =json, and =yaml.

### Provide a possible output or UX example

I should be able to run `pyflyte register --remote somewf_dir --output=json` 
and the following output.json file should exist in the repo
```json
[{"type":"workflow", "name":"somewf_dir.workflow_file.wf", "version":"abcd123"}, {"type":"task", "name":"somewf_dir.workflow_file.task_a", "version":"abcd123"}]
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

### PR DESCRIPTION
**Pull request by adarsh-jha-dev**
## Tracking issue

closes #3919 

## Describe your changes

In the start.go file, I introduced a new command, flyte single start, which is used to start a Flyte cluster locally. This command includes the following key changes:

- The startCmd variable is defined to create a new Cobra command named "start." It has a brief description indicating its purpose.
- Inside the RunE function of this command, an error group (errgroup) is created, and the childCtx context is derived from the parent context (ctx).
- You access the configuration using the GetConfig() function to retrieve the configuration settings for different components such as Admin, Propeller, and DataCatalog.
- Three different components are started in parallel if they are not explicitly disabled in the configuration:
- Admin: The Flyte Admin server, including database migrations and seeding of default projects.
- Propeller: The Flyte Propeller component, including its controller and webhook server.
- DataCatalog: The Flyte DataCatalog component, including database migrations.
- The errgroup (g) is used to coordinate the start of these components in parallel.
- Finally, the function waits for all the components to complete by calling g.Wait().

This change allows users to conveniently start a Flyte cluster locally using a single command while providing the flexibility to disable specific components as needed.

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] All commits are signed-off.

## Screenshots
N/A

## Note to reviewers

Please review this and let me know if the changes are relevant to the issue. Your feedback is greatly appreciated.

### CODE REVIEW

**Comment by samhita-alla** [comment]
@adarsh-jha-dev, this PR doesn't look correct to me. It isn't even related to the issue you mentioned.

**Comment by adarsh-jha-dev** [comment]
Sorry for the inconvenience caused, i misunderstood the issue. I will raise another PR for this with valid changes

**Comment by adarsh-jha-dev** [comment]
> @adarsh-jha-dev, this PR doesn't look correct to me. It isn't even related to the issue you mentioned.

@samhita-alla , could you please help me find the relevant source code for this issue, I am unable to find it.

**Comment by samhita-alla** [comment]
Looks like a PR has already been created for the same issue.

**Pull request closed without merging**
