### PR TITLE
Adding screenshot of updated Getting Started page

### PR DESCRIPTION
**Pull request by SandraGH5**
Uploading screenshot of updated Getting Started page to be used on Contributing to Flyte page.

### CODE REVIEW

**Comment by kumare3** [comment]
We should upload it to static resources

**Comment by SandraGH5** [comment]
> We should upload it to static resources

It has been uploaded to static resources - just under the same name as the previous image (docs_edit). The old image has been deleted.

**Comment by SandraGH5** [comment]
Here?
https://github.com/flyteorg/flyte/blob/static-resources/img/contribution_guide/docs_edit.png

**Comment by EngHabu** [comment]
We no longer need this PR since you already updated the static-resources repo [here](https://github.com/flyteorg/flyte/pull/2083). Closing

**Pull request closed without merging**
