### PR TITLE
Updates to auth docs

### PR DESCRIPTION
**Pull request by davidmirror-ops**
## Tracking issue

This PR completes the work initiated on #3062 

## Check all the applicable boxes 

- [X] I updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] All commits are signed-off.

## Note to reviewers

Content as per the lastest review in #3062.

### CODE REVIEW

**Comment by wild-endeavor** [comment]
Could you take a look at the docs test failure?  It's complaining about `/home/runner/work/flyte/flyte/rsts/deployment/configuration/auth_setup.rst:25:undefined label: auth-openid-appendix`

Thanks

**Review by wild-endeavor — APPROVED** [review]

**Comment by davidmirror-ops** [comment]
> Could you take a look at the docs test failure? It's complaining about `/home/runner/work/flyte/flyte/rsts/deployment/configuration/auth_setup.rst:25:undefined label: auth-openid-appendix`
> 
> Thanks


@wild-endeavor  I think I finally fixed all the problematic references :)

**Comment by alexifm** [comment]
Hey, so I went through a lot of disparate sources to piece together a deployment on EKS that seems to work.  Here is my repo for that:
https://github.com/alexifm/flyte-eks-deployment

Regarding this set of instructions:
https://github.com/flyteorg/flyte/pull/3363/files#diff-ee77fbe074a2e541ba69e70ac154aa8fcffcdc3699cb4f0abc8379e4ee2a3b9bR191-R195

That doesn't appear to match with the repo's `values.yaml` file: https://github.com/flyteorg/flyte/blob/master/charts/flyte-core/values.yaml

Also, if you look at the `values-auth.yaml` file that I've produced (as I said, cobbled together from various Slack and Discuss threads), the suggestion in the PR appears inadequate.

https://github.com/alexifm/flyte-eks-deployment/blob/main/values-auth.yaml

One caveat is, I'm using the internal self authorization.  Setting up the authorization server is described as "optional" though so in my opinion, if you set OpenID, you should have a working deployment.  But that initial section that sets up OpenID doesn't seem to provide someone with a complete solution with the internal self authorization operational.

**Comment by wild-endeavor** [comment]
@alexifm mind if we merge this PR first and iterate?  it's already much more accurate than what we have right now.

**Comment by alexifm** [comment]
Don't mind at all.  Just wanted to provide feedback from my experience.

**Pull request closed without merging**
