### PR TITLE
Enable caching in flyte-core helmchart

### PR DESCRIPTION
**Pull request by cpaulik**
## Why are the changes needed?

Without this caching was actually not enabled when deploying with the flyte-core helm chart

## What changes were proposed in this pull request?

Adding `storage` to the `cache.yaml` file so that the [configuration values](https://docs.flyte.org/en/latest/deployment/configuration/generated/flytepropeller_config.html#cache-storage-cachingconfig) for `storage.cache.max_size_mbs` and `storage.cache.target_gc_percet` are picked up correctly

## How was this patch tested?

I've deployed flyte core without this change and caching was not enabled. After I added 

```
configmap:
  core:
    storage:
      cache:
        max_size_mbs: 5000
        target_gc_percent: 70
```

caching started working so I assume that adding `storage` in the `cache.yaml` would also work.

### CODE REVIEW

**Comment by cpaulik** [comment]
For DCO I'm waiting for our legal department so this might take a bit for the first contribution.

**Comment by cpaulik** [comment]
DCO should be fixed

**Review by pingsutw — APPROVED** [review]
LGTM, thank you for fixing it

**Comment by davidmirror-ops** [comment]
@cpaulik Thank so much! Also to fix the problem detected by generate_helm, you should be able to run `make helm` in your fork and push the changes

**Comment by cpaulik** [comment]
I ran `make helm` and updated the commit

**Review by eapolinario — APPROVED** [review]
Thank you.

**Pull request merged**
