### PR TITLE
Fix and update scripts for generating grafana dashboards

### LINKED ISSUE #4346: [BUG] Grafana dashboards are outdated and `make stats` is failing
### Describe the bug

The Grafana dashboards [here](https://grafana.com/grafana/dashboards/?search=flyte) are outdated. It seems like they were last updated 2 years ago and that a lot of metrics referenced there have been renamed or are not being produced anymore.
I tried running `make stats` to generate an updated version, but I'm getting the following error:

```
Traceback (most recent call last):
  File "/home/victor.delepine/.local/bin/generate-dashboard", line 8, in <module>
    sys.exit(generate_dashboard_script())
  File "/home/victor.delepine/.local/lib/python3.8/site-packages/grafanalib/_gen.py", line 242, in generate_dashboard_script
    run_script(generate_dashboard)
  File "/home/victor.delepine/.local/lib/python3.8/site-packages/grafanalib/_gen.py", line 80, in run_script
    sys.exit(f(sys.argv[1:]))
  File "/home/victor.delepine/.local/lib/python3.8/site-packages/grafanalib/_gen.py", line 223, in generate_dashboard
    dashboard = loader(opts.dashboard)
  File "/home/victor.delepine/.local/lib/python3.8/site-packages/grafanalib/_gen.py", line 74, in loader
    raise DefinitionError(
grafanalib._gen.DefinitionError: Definition /tmp/flyte/stats/flytepropeller_dashboard.py does not define a variable '/tmp/flyte/stats/flytepropeller_dashboard'
make: *** [Makefile:62: stats] Error 1
```
(Please disregard the `/tmp/` path, I was trying to check something else)

Example of outdated metrics: all the flyte:admin:database:postgres:repositories:* are now under flyte:admin:admin:database:*

Most metrics that measure durations like `flyte:propeller:all:workflow:failure_duration_ms` need to be prefixed by "unlabeled", like: `flyte:propeller:all:workflow:failure_duration_unlabeled_ms`.
A lot of Flyte Admin metrics need a second "admin" prefix: `flyte:admin:list_launch_plan:codes:OK` becomes `flyte:admin:admin:list_launch_plan:codes:OK`

### Expected behavior

The Grafana dashboards should be in sync with the state of prometheus metrics in the repo

### Additional context to reproduce

_No response_

### Screenshots

_No response_

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

### PR DESCRIPTION
**Pull request by Tom-Newton**
## Tracking issue

Closes #4346

## Describe your changes
- Rename dashboard generation files so that grafana lib's `generate-dashboard` command works correctly. Previously we were getting `grafanalib._gen.DefinitionError: Definition /tmp/flyte/stats/flytepropeller_dashboard.py does not define a variable '/tmp/flyte/stats/flytepropeller_dashboard'`
- Update generation scripts where the metric names have changed. 
- Add a multiply by 100 on some graphs that where supposed to show percentage. 
- Ensure RefIds are unique. I was getting errors from grafana when trying to view these dashboards. 
- Update the checked in dashboard `json`s
- I based all these changes on a `flyte-core` deployment. The metric names might be difference on `flyte-binary`
- Changed the aggregation from sum to max on the flyteadmin latencies. Sum would always return a blank graph when using more than one flyteadmin replica. 

## Check all the applicable boxes 

- [x] I updated the documentation accordingly - I think the documentation was already correct
- [ ] All new and existing tests passed - perhaps we could add a test to ensure `make stats` works but probably it will be difficult to check that all the metric names are correct
- [x] All commits are signed-off.

## Screenshots
image

## Note to reviewers
I went through all the graphs in the dashboards to confirm either they have data or there is a valid reason for them not to show anything and that the metrics they use are exposed by flyte.

### CODE REVIEW

**Comment by eapolinario** [comment]
This is amazing! Thank you!

One thing that's still not clear is how these dashboards are published. I'm not sure if we were doing it manually or if there was some automation somewhere (I couldn't find anything in the `flyte` main repo).

**Comment by Tom-Newton** [comment]
> One thing that's still not clear is how these dashboards are published. I'm not sure if we were doing it manually or if there was some automation somewhere (I couldn't find anything in the `flyte` main repo).

According to this README they are published manually.

**Comment by Tom-Newton** [comment]
I've just discovered a problem with the flyteadmin dashboard. It seem like latency metrics are not aggregated correctly if you are running flyteadmin with more than one replica. I will try to push a fix.

**Review by eapolinario — APPROVED** [review]
This is great, thank you!

**Pull request merged**
