### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by eapolinario**

### CODE REVIEW

**Comment by kumare3** [comment]
@eapolinario thank you for the PR, you need to DCO, as per LF guidelines. if you used the web-editor that usually does not work unless you add a chrome plugin

**Comment by kumare3** [comment]
BTW we should enable spellcheck for Sphinx - https://pypi.org/project/sphinxcontrib-spelling/

**Comment by eapolinario** [comment]
https://github.com/flyteorg/flyte/blob/a9807c8d1b0d5564b63b8fe92704bb5d9b045942/.github/workflows/tests.yml#L12-L13 seems to be failing with:
```
 /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +79eab92e3de0af86357237fa60978dc70acfbd2a:refs/remotes/pull/1178/merge
  remote: Internal Server Error.
  remote: 
  Error: fatal: unable to access 'https://github.com/flyteorg/flyte/': The requested URL returned error: 500
  Error: The process '/usr/bin/git' failed with exit code 128
```

Maybe related to https://github.com/flyteorg/flyte/pull/1087?

**Comment by kumare3** [comment]
how can that be? the tests in master are successful

**Pull request closed without merging**
