### PR TITLE
[WIP] [Docs] Add usage for jupyter notebook interactive mode

### PR DESCRIPTION
**Pull request by Mecoli1219**
## Tracking issue
https://github.com/flyteorg/flyte/issues/5907

## Screenshots
image

## Check all the applicable boxes 

- [x] I updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Docs link
https://flyte--5997.org.readthedocs.build/en/5997/user_guide/flyte_fundamentals/running_and_scheduling_workflows.html

### CODE REVIEW

**Comment by Mecoli1219** [comment]
@samhita-alla @davidmirror-ops How does this look? (I am using a hacky way now. I'm unsure if there is any other appropriate method to render a cell from Jupyter Notebook.)

image

**Comment by Future-Outlier** [comment]
Michael, you are 絕活哥

**Comment by samhita-alla** [comment]
@Mecoli1219 thanks so much for working on this! have you tried using https://docs.readthedocs.io/en/stable/guides/jupyter.html#using-notebooks-in-other-formats since `myst-nb` is already enabled as a sphinx extension?

**Comment by Mecoli1219** [comment]
@samhita-alla I realize the link you provided renders the entire jupytext format file as a single sphinx page. What I'm specifically looking for is rendering just one cell from an ipynb file, ideally with a link to the flytesnacks example. (Previously this worked with `rli`/`remoteliteralinclude`, but since we've switched to `literalinclude`, we lost the linking capability).

Thinking about it now, I may be overcomplicating this. We could simply write similar example code directly in our docs like in my screenshot.

What are your thoughts on the `interactive_mode` documentation - should we include the complete example, or would it be better to just show the basic usage (like in my screenshot) and perhaps provide links to flytesnacks for more detailed examples?

**Comment by davidmirror-ops** [comment]
@Mecoli1219 I'd vote for rendering the notebook as a page if that's simpler. The benefit is that the notebook in flytesnacks would be "self contained" with code and instructions in a single place.

**Comment by Mecoli1219** [comment]
Closed as the alternative PR is created: https://github.com/flyteorg/flyte/pull/6036

**Pull request closed without merging**
