### PR TITLE
Update schedules.md

### PR DESCRIPTION
**Pull request by RaghavMangla**
## Why are the changes needed?

delete documentation related to AWS scheduler configuration, as the flyte native scheduler should just work.

reference slack thread: https://discuss.flyte.org/t/15852550/hi-team-i-have-created-a-simple-test-flyte-scheduler-using-b#929e7edd-c801-4dbb-bdbf-61cb36903727

Issue Link: https://github.com/flyteorg/flyte/issues/4513
Closes  https://github.com/flyteorg/flyte/issues/4513

### Screenshots
image

## Check all the applicable boxes 

- [x] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] All commits are signed-off.

## Docs link
Changes made in schedules.md: https://github.com/flyteorg/flyte/edit/master/docs/user_guide/productionizing/schedules.md

### CODE REVIEW

**Comment by RaghavMangla** [comment]
@neverett @ppiegaze @samhita-alla pls review this pr

**Comment by neverett** [comment]
This looks good to me, but @samhita-alla I wanted to double check what you meant by "move to the legacy section" in the linked issue -- do you think this content should remain on the page, just under a "Legacy" heading?

**Comment by RaghavMangla** [comment]
Hi! @neverett actually in this issue https://github.com/flyteorg/flyte/issues/4513 it was mentioned to delete the aws scheduler part in documentation, so i removed that part from documentation

**Comment by RaghavMangla** [comment]
@neverett @ppiegaze pls review the PR

**Comment by RaghavMangla** [comment]
All checks have passed , please let me know if any changes are required

**Comment by samhita-alla** [comment]
@neverett i think it should be okay to delete the docs. we don't need to preserve it anymore.

**Review by samhita-alla — APPROVED** [review]

**Comment by RaghavMangla** [comment]
@all-contributors please add my github account RaghavMangla for contributions

**Comment by RaghavMangla** [comment]
https://github.com/all-contributors please add my github account RaghavMangla for contributions docs
https://github.com/flyteorg/flyte/pull/5826
https://github.com/flyteorg/flytekit/pull/2791
https://github.com/flyteorg/flytesnacks/pull/1742

**Pull request merged**
