### PR TITLE
remove lb

### PR DESCRIPTION
**Pull request by brucearctor**
I actually didn't do 100% checking ... but ... are these Load Balancers needed? 

[ they cause problems with opta, and at a first pass I don't see why they are required ]

### CODE REVIEW

**Comment by EngHabu** [comment]
These are not needed..

@evalsocket, I recall you went ahead and cleaned these up? was that for a specific provider?

**Comment by brucearctor** [comment]
@evalsocket -- ran `make helm` which looks like created more failures :-)

**Review by evalsocket — APPROVED** [review]
Thank you

**Comment by brucearctor** [comment]
Needs someone to merge ( since I don't have permissions, even though @evalsocket already approved ).  

That invites the question -- what are merge policies for Flyte?  I don't see documentation specifying those criteria.

**Comment by EngHabu** [comment]
Had to rerun the WFs,... seems there was an issue earlier today with github actions (based on this https://www.githubstatus.com/incidents/8xxms3q3qzgp) not sure if's related

**Comment by jw0515** [comment]
This breaks the https://docs.flyte.org/en/latest/deployment/aws/manual.html#connecting-to-flyte

Now we will have to add: #      alb.ingress.kubernetes.io/target-type: 'ip' in the ingress annotation

@brucearctor 
@EngHabu

**Comment by brucearctor** [comment]
@jw0515 -- based on my experience, that change did not break the UI, flytectl, nor flyteconfig/pyflyte.  But, that doesn't mean that it didn't create a problem outside of my workflows.

**Comment by jw0515** [comment]
> @jw0515 -- based on my experience, that change did not break the UI, flytectl, nor flyteconfig/pyflyte. But, that doesn't mean that it didn't create a problem outside of my workflows [ hence the reason for more tests, and specifically for the steps in the deployment guide ].

Thanks for your reply! Yes the thing is ingress creation will have some issue:
when I do `kubectl -n flyte get ingress`, I won't get any address

**Comment by brucearctor** [comment]
I wonder whether another way to 'solve' your issue might be updating docs?  

I think you can use the loadbalancer's DNS, and `kubectl -n flyte get ingress` ingress not required.

**Comment by jw0515** [comment]
In this case the AWS ALB won't be created at all...so no DNS

**Comment by brucearctor** [comment]
hmmm; I was working with https://docs.flyte.org/en/latest/deployment/aws/opta.html ( even though terraform > opta, opta was the pre-existing committment ).  And working with that, LB gets created.  So, again, probably a docs thing.  

I imagine it'll be better if there are just ready-to-go terraform modules.  But, seems worth also determining whether manual ( ex: by `aws ...` commands also needs to be updated, and automated tests written and maintained

**Pull request merged**
