### PR TITLE
Fix broken links in documentation

### PR DESCRIPTION
**Pull request by wanderer163**

### CODE REVIEW

**Comment by kumare3** [comment]
@wanderer163 thank you, but this part of the docs is deprecated. Thank you for pointing it to us.

Cc @EngHabu / @evalsocket wgats the plan here?

**Comment by evalsocket** [comment]
@wanderer163 Please run `make kustomize` and then commit the changes. it will fix the checks.

**Comment by evalsocket** [comment]
@kumare3 it's almost deprecated. We are not adding new features but I am not sure how many people are dependent on old kustomize deployment.  officially we didn't announce anything related to the deprecation of kustomize.

**Comment by kumare3** [comment]
@evalsocket i agree. What I meant was that in our deployment page should we point to the kustomize and say it's not maintained, but ymmv

**Review by EngHabu — APPROVED** [review]

**Pull request merged**
