### PR TITLE
charts: honor redoc.enabled=false

### LINKED ISSUE #4006: [BUG] Helm redoc templates - flyte chart - not honoring redoc.enabled in values
### Describe the bug

When installing the `flyte` chart and setting `redoc.enabled` to `false`, the `redoc` deployment and service is still installed.

The problem is in the `charts/flyte/templates/redoc/deployment.yaml` and `charts/flyte/templates/redoc/deployment.yaml`. These need to be wrapped by a conditional on the `rdoc.enabled` value, like it is done with other templates (for example, `templates/redis`).

### Expected behavior

No `redoc` deployment when installing the `flyte` chart with `redoc.enabled` set to `false`.

### Additional context to reproduce

```shell
helm repo add flyteorg https://flyteorg.github.io/flyte
helm repo update
helm upgrade flyte -n flyte flyteorg/flyte \
    --set redoc.enabled=false \
    --dry-run > flyte.yaml
cat flyte.yaml| grep "name: redoc"
```

Above command should not output the `redoc` deployment and service.

### Screenshots

_No response_

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

### PR DESCRIPTION
**Pull request by flixr**
charts: honor `redoc.enabled=false` and also use correct nodeSelector and fix doc

## Tracking issue

Example: Closes #4006

Updated version of #2982

## Why are the changes needed?

See #4006

## Check all the applicable boxes 

- [x] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] All commits are signed-off.

### CODE REVIEW

**Review by pingsutw — APPROVED** [review]
LGTM, Thank you

**Review by eapolinario — DISMISSED** [review]

**Comment by eapolinario** [comment]
@flixr , can you take a look at [this CI](https://github.com/flyteorg/flyte/actions/runs/9397470919/job/25907236251?pr=5452) failure?

**Comment by flixr** [comment]
@eapolinario so if I understand that correctly, I also need to update the generated charts and README to match the changes? Is there some script to do that?

**Comment by pingsutw** [comment]
@flixr `make helm` will generate that

**Comment by flixr** [comment]
@pingsutw I ran `script/generate_helm.sh`

**Pull request merged**
