### PR TITLE
Update Sequence diagram

### LINKED ISSUE #2804: [Docs] Broken image for external authorization server
### Description

Following page https://docs.flyte.org/en/latest/deployment/cluster_config/auth_appendix.html#service-authentication-using-oauth2 has broken image 
Screenshot 2022-08-24 at 5 21 43 PM

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

### PR DESCRIPTION
**Pull request by Smartmind12**
Signed-off-by: Utsav Paul <91927689+Smartmind12@users.noreply.github.com>

## Tracking issue

Closes #2804 

## Describe your changes

Made the Sequence diagram uniform so that image does not break.

## Check all the applicable boxes 

- [X] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] All commits are signed-off.

## Note to reviewers

@samhita-alla @pingsutw Kindly review the PR and let me know if any changes needed ...Thanks!

### CODE REVIEW

**Comment by samhita-alla** [comment]
@Smartmind12, thanks for creating the PR! But I feel the diagram is still unclear. Can you ensure the blocks in the second row are displayed and the arrows do not overlap with the blocks like FlyteAdmin’s built-in Authorization Server diagram? I'd also like the external auth server diagram in https://docs.flyte.org/en/latest/deployment/cluster_config/auth_appendix.html#user-authentication-in-other-clients-e-g-cli-using-oauth2-pkce section to be updated.

**Comment by Smartmind12** [comment]
> @Smartmind12, thanks for creating the PR! But I feel the diagram is still unclear. Can you ensure the blocks in the second row are displayed and the arrows do not overlap with the blocks like FlyteAdmin’s built-in Authorization Server diagram? I'd also like the external auth server diagram in https://docs.flyte.org/en/latest/deployment/cluster_config/auth_appendix.html#user-authentication-in-other-clients-e-g-cli-using-oauth2-pkce section to be updated.

SequenceDiagram
I had created this Sequence Diagram on draw.io which is way easier than rst but i am finding it difficult to edit the rst file.

**Comment by samhita-alla** [comment]
@Smartmind12, we'll need to build the image with sphinx-mermaid so that it's configurable. Can you go through the [mermaid docs](https://mermaid-js.github.io/mermaid/#/) and see how we can fix the diagrams?

**Comment by Smartmind12** [comment]
> sphinx-mermaid

I checked the syntax and run the suntax on the mermaid editor and works absolutely fine. The issue is of mermaid not working perfectly with rst files. So either convert rst files to markdown or we need to search another way around!

**Comment by samhita-alla** [comment]
Created a [PR](https://github.com/flyteorg/flyte/pull/3033) on top of this to fix the issue.

**Pull request closed without merging**
