### PR TITLE
update scroll behavior so that sidebar maintains location

### LINKED ISSUE #5197: [BUG] Auto refreshing on change tabs
### Describe the bug

Flyte docs keeps auto-refreshing when switching tab

### Expected behavior

should not auto refresh

### Additional context to reproduce

_No response_

### Screenshots

https://github.com/flyteorg/flyte/assets/37936015/2e444626-99dd-4b26-9374-4859b75d805e

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

### PR DESCRIPTION
**Pull request by cosmicBboy**
## Tracking issue
Fixes #5197

## Why are the changes needed?

Currently in the [docs](https://docs.flyte.org/en/latest/) the sidebar location is lost whenever you navigate to a new page. See #5197 for details.

## What changes were proposed in this pull request?

Add custom javascript logic so that the sidebar location is maintained when you navigate across pages.

## How was this patch tested?

Running `make docs` locally.

## Check all the applicable boxes 

- [x] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] All commits are signed-off.

### CODE REVIEW

**Comment by cosmicBboy** [comment]
docs ci issue is unrelated
```
module 'mlflow' has no attribute 'MlflowClient'
```

**Review by pingsutw — APPROVED** [review]
Thank you so much!

**Comment by cosmicBboy** [comment]
@pingsutw mind +1'ing again?

**Review by Future-Outlier — APPROVED** [review]
Thank you.

**Pull request merged**
