### PR TITLE
Fix lint errors caught by `chart-testing`

### PR DESCRIPTION
**Pull request by eapolinario**
## Tracking issue
NA

## Why are the changes needed?
We enabled chart testing in https://github.com/flyteorg/flyte/pull/5027, but never got around fixing the lint errors caught by that check. This PR fixes the first batch of errors.

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] All commits are signed-off.

### CODE REVIEW

**Comment by lowc1012** [comment]
@eapolinario thanks
I also created a PR for this issue.
https://github.com/flyteorg/flyte/pull/5068

**Comment by eapolinario** [comment]
> @eapolinario thanks I also created a PR for this issue. #5068

oh nice, thank you. I didn't notice you were also fixing this. I took a look and it looks like we're duplicating some areas (sorry about that!). Unfortunately we need those comments as those are used as part of the [release process](https://github.com/flyteorg/flyte/blob/master/script/release.sh#L12-L31).

**Review by davidmirror-ops — APPROVED** [review]
Is there a way to test this?
Thanks!

**Comment by eapolinario** [comment]
> Is there a way to test this? Thanks!

Are you asking about testing this locally? If so, I'm adding a make target that runs this job locally using [act](https://github.com/nektos/act). This will help us iterate locally (and decrease the discrepancy between CI and local tests).

**Pull request merged**
