### PR TITLE
Revert "Improve execution name readability"

### PR DESCRIPTION
**Pull request by pingsutw**
## Tracking issue
NA

## Why are the changes needed?
Using a friendly name has a high possibility of collision.

Note: We plan to add another column to the execution table to store this friendly name. FlyteConsole can get the friendly name from GetExecutionRequest/ListExecutionRequest and display it in a separate column on the execution page.

## What changes were proposed in this pull request?
Revert the commits 

## How was this patch tested?
uni test

## Check all the applicable boxes 

- [x] I updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Related PRs
NA

## Docs link
NA

### CODE REVIEW

**Comment by pingsutw** [comment]
cc @eapolinario

**Comment by pingsutw** [comment]
cc @ddl-ebrown

**Comment by pingsutw** [comment]
We did the math for 4 words + the 6 character suffix, and found it still has a high possibility of having collisions when you have more than 1 million workflows. @eapolinario can share more details.

**Comment by pingsutw** [comment]
cc @eapolinario can we merge this

**Comment by eapolinario** [comment]
> cc @eapolinario can we merge this

for sure. I'll do it asap.

**Review by eapolinario — APPROVED** [review]

**Comment by wayner0628** [comment]
Hello! I contributed to the previous PR and have been focusing on other work, but I’d love to know the current progress on this. Is @eapolinario already working on a new PR for this issue?

Regarding the use of a 4-character nanoid, based on my calculations, it would yield 2^32 * 64^4 = 2^(32+24) = 2^56. This seems to be insufficient compared to N = 95 from the original hashes. Does this mean we will proceed with the middle-ground solution?

**Comment by wayner0628** [comment]
Hi @eapolinario and @pingsutw,

Before I start working on this task, I wanted to confirm a few details to ensure my approach aligns with your expectations:

- **For the single execution page**, would you like the friendly name to be included as part of the metadata, or would you prefer it to be displayed next to the hashed execution name?
  Screenshot 2024-10-22 at 5 23 09 PM

- **For the executions overview page**, should the friendly name be displayed as shown in the image? I’m concerned it might compete for space with other information on the page.
  Screenshot 2024-10-22 at 5 26 47 PM

Let me know your thoughts so I can proceed accordingly!

**Pull request merged**
