### PR TITLE
[Docs] Testing agents in the development environment

### PR DESCRIPTION
**Pull request by Future-Outlier**
## Docs link
index: https://flyte--5106.org.readthedocs.build/en/5106/flyte_agents/index.html
testing_agents_in_the_development_environment: https://flyte--5106.org.readthedocs.build/en/5106/flyte_agents/testing_agents_in_the_development_environment.html
deploying_agents_to_the_flyte_sandbox: https://flyte--5106.org.readthedocs.build/en/5106/flyte_agents/deploying_agents_to_the_flyte_sandbox.html
implementing_agent_metadata_service: https://flyte--5106.org.readthedocs.build/en/5106/flyte_agents/implementing_agent_metadata_service.html

## Tracking issue
https://github.com/flyteorg/flyte/issues/3936

## Why are the changes needed?
Help users to develop agent service and test it more easily.

## What changes were proposed in this pull request?
Add `Testing agents in the development environment` documentation.

## How was this patch tested?
@samhita-alla has tested it when developing the aws sagemaker agent, and it works well

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] All commits are signed-off.

## Related PRs
https://github.com/flyteorg/static-resources/pull/37

### CODE REVIEW

**Comment by neverett** [comment]
Hey @Future-Outlier sorry for the delay on reviewing this -- would you be able to add your changes from https://github.com/flyteorg/flyte/pull/5107/ to this PR so the combined changes can be reviewed together?

**Comment by Future-Outlier** [comment]
> Hey @Future-Outlier sorry for the delay on reviewing this -- would you be able to add your changes from #5107 to this PR so the combined changes can be reviewed together?

I've just merged it, thank you for reviewing this PR.
I will update your suggestion ASAP.

**Comment by Future-Outlier** [comment]
@neverett Hi, will you review these docs recently?
It is really ok that you don't have time to do it.
I am thinking that we can merge this PR first since some users want this documentation to write their own agent.

**Comment by neverett** [comment]
@Future-Outlier would it be okay if I pushed commits to this branch? I think it will be faster for me to reorganize some of the information that way.

**Comment by Future-Outlier** [comment]
> @Future-Outlier would it be okay if I pushed commits to this branch? I think it will be faster for me to reorganize some of the information that way.

it will be okay

**Comment by Future-Outlier** [comment]
> @Future-Outlier would it be okay if I pushed commits to this branch? I think it will be faster for me to reorganize some of the information that way.

@neverett feel free to do that, thank you!

**Review by neverett — APPROVED** [review]

**Comment by neverett** [comment]
@Future-Outlier I pushed a commit to reorganize and edit the content -- let me know what you think! If my changes look good to you and tests are passing, feel free to merge.

**Comment by Future-Outlier** [comment]
> @Future-Outlier I pushed a commit to reorganize and edit the content -- let me know what you think! If my changes look good to you and tests are passing, feel free to merge.

@neverett It's great, thank you!

**Pull request merged**
