### PR TITLE
add accelerator docs

### PR DESCRIPTION
**Pull request by cosmicBboy**
This PR adds accelerator docs to the monodocs toctree.

### CODE REVIEW

**Review by thomasjpfan — COMMENTED** [review]
This looks like `flyte` needs to be manually updated when a new top level document is added to `flytekit`. Can `docs/reference_flytekit.md` be generated from something checked into from `flytekit`?

**Comment by cosmicBboy** [comment]
> This looks like flyte needs to be manually updated when a new top level document is added to flytekit. Can docs/reference_flytekit.md be generated from something checked into from flytekit?

Yeah we can add a new top-level index page to `flytekit` instead of flyte, this PR is just a stop-gap

**Review by thomasjpfan — COMMENTED** [review]
The failing [CI test](https://github.com/flyteorg/flyte/actions/runs/7477465881/job/20350202775?pr=4713) looks related. Is this expected?

**Comment by cosmicBboy** [comment]
> The failing [CI test](https://github.com/flyteorg/flyte/actions/runs/7477465881/job/20350202775?pr=4713) looks related. Is this expected?

Hmm, I think because of https://github.com/flyteorg/flyte/commit/b35f792636e3733e9f77c3cbc0fcf36a0f431bd9 the build process is using the latest stable release (which doesn't have the accelerator docs).

Might just opt for doing the right thing here.

**Comment by thomasjpfan** [comment]
I am closing this PR because the issue was resolved in https://github.com/flyteorg/flyte/pull/4720

**Pull request closed without merging**
