### PR TITLE
Update contributors' section

### PR DESCRIPTION
**Pull request by samhita-alla**
Signed-off-by: Samhita Alla <aallasamhita@gmail.com>

Preview: https://github.com/flyteorg/flyte/blob/b37b14af0e047d2627e44a63e3cbe179627c3826/README.md#-top-contributors

### CODE REVIEW

**Comment by kumare3** [comment]
This is auto generated right? Can we write this to contributing docs of how to add contributors?

**Comment by wild-endeavor** [comment]
I don't really like my picture on there but I guess that's okay.  I'm not a fan of the emojis though... it feels super cluttered.

**Comment by kumare3** [comment]
@wild-endeavor / @katrogan the emojis are a [allcontributors.org](https://allcontributors.org/docs/en/overview) thing

**Comment by samhita-alla** [comment]
> This is auto generated right? Can we write this to contributing docs of how to add contributors?

The "Add a Contributor" section is now up.

**Comment by samhita-alla** [comment]
> I don't really like my picture on there but I guess that's okay. I'm not a fan of the emojis though... it feels super cluttered.

@wild-endeavor Haha, your GitHub profile picture gets picked up automatically. If you want a different picture, you'd have to change your GitHub profile picture.

@katrogan @SandraGH5 I've added a key to the emojis.

Also, you want me to reduce the number of emojis per profile? Say, restrict it to three?

**Comment by SandraGH5** [comment]
> > I don't really like my picture on there but I guess that's okay. I'm not a fan of the emojis though... it feels super cluttered.
> 
> @wild-endeavor Haha, your GitHub profile picture gets picked up automatically. If you want a different picture, you'd have to change your GitHub profile picture.
> 
> @katrogan @SandraGH5 I've added a key to the emojis.
> 
> Also, you want me to reduce the number of emojis per profile? Say, restrict it to three?

I wouldn't reduce the number of emojis, but is it possible to introduce some white space between the rows and/or columns of the contributors, to space them out a bit and reduce the feeling of it being cluttered?

**Comment by kumare3** [comment]
I think the emoji or the idea is useful. Its like a badge, we should encourage more folks to get those emojis!

**Comment by samhita-alla** [comment]
> I wouldn't reduce the number of emojis, but is it possible to introduce some white space between the rows and/or columns of the contributors, to space them out a bit and reduce the feeling of it being cluttered?

@SandraGH5 I don't think it is possible. The styles wouldn't apply for README.

**Comment by kumare3** [comment]
@samhita-alla I like this stuff - how do we proceed?

**Comment by kumare3** [comment]
also we need to include new folks. What we have is old, now we have more contributors. ideally, automatic would be awesome!

**Comment by samhita-alla** [comment]
@kumare3 I think we can merge this PR. We just have to comment on an issue or PR for new folks, which I have included in the contribution guide https://github.com/flyteorg/flyte/pull/1329/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055.

**Pull request closed without merging**
