### PR TITLE
Added flyte-core helm chart 

### PR DESCRIPTION
**Pull request by evalsocket**
- Added flyte-core helm chart 
- Added flyte-sandbox helm charts
- Refactor dir structure of helm 
- Refactore GitHub workflow for helm release

Tested Workflow: https://github.com/evalsocket/flyte/runs/3204455176?check_suite_focus=true
Registry : https://github.com/evalsocket/flyte/blob/gh-pages/index.yaml
Docs: https://hackmd.io/VijmURvVRiu4qOOH2XdcDg?view

## Test Helm charts:
```bash
helm repo add flyte https://evalsocket.github.io/flyte
helm install -n flyte -f values-eks.yaml --create-namespace flyte flyte/flyte
```

## Install contour: 
```bash
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install gateway bitnami/contour -n flyte  
```

## Install the ingress
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flyte-gateway
  namespace: flyte
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: flyteconsole
            port:
              number: 80
        path: /__webpack_hmr
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 87
        path: /openapi
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteconsole
            port:
              number: 80
        path: /console
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteconsole
            port:
              number: 80
        path: /console/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 80
        path: /api
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 80
        path: /api/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 80
        path: /healthcheck
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 80
        path: /v1/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 80
        path: /openapi/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 80
        path: /.well-known
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 80
        path: /.well-known/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 80
        path: /login
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 80
        path: /login/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 80
        path: /logout
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 80
        path: /logout/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 80
        path: /callback
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 80
        path: /callback/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 80
        path: /me
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 80
        path: /config
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 80
        path: /config/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 80
        path: /oauth2
        pathType: ImplementationSpecific
      - backend:
          service:
            name: flyteadmin
            port:
              number: 80
        path: /oauth2/*
        pathType: ImplementationSpecific
```

## Install spark Operator 
```bash
 helm repo add spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator
  helm install spark spark-operator/spark-operator --namespace spark-operator -n flyte
```
## Values-eks changes for spark
```yaml
configmap:
  enabled_plugins:
    # -- Tasks specific configuration [structure](https://pkg.go.dev/github.com/flyteorg/flytepropeller/pkg/controller/nodes/task/config#GetConfig)
    tasks:
      # -- Plugins configuration, [structure](https://pkg.go.dev/github.com/flyteorg/flytepropeller/pkg/controller/nodes/task/config#TaskPluginConfig)
      task-plugins:
        # -- [Enabled Plugins](https://pkg.go.dev/github.com/lyft/flyteplugins/go/tasks/config#Config). Enable sagemaker*, athena if you install the backend
        # plugins
        enabled-plugins:
          - container
          - sidecar
          - spark
          - k8s-array
        default-for-task-types:
          container: container
          sidecar: sidecar
          spark: spark
          container_array: k8s-array
  
  
 sparkoperator:
  # --- enable or disable Sparkoperator deployment installation
     enabled: true        
```

## Run Sandbox
```bahs
helm install -n flyte -f values.yaml --create-namespace flyte flyte/flyte-sandbox
```

NOTE: sagemaker, tf_operator, pytorchoperator Is not tested with these workflow....I assume all those plugin will also work

### CODE REVIEW

**Comment by sbrunk** [comment]
I think it's great to have better modularization but it seems the the core chart is now essentially duplicated right? I'd like to avoid having to keep things in sync manually if possible so perhaps we can find a way to avoid that duplication.

**Comment by evalsocket** [comment]
@sbrunk yes that's the idea. We will only have one chart for flyte-core.  Sandbox chart will have dependence on flyte-core.

Currently our helm chart have dependency but in reality  flyte doesn't have any dependency. Flyte will work without all the dependency that we have in our current chart.

**Comment by pmahindrakar-oss** [comment]
Lets also test the manual and opta deployments work with these changes.
https://docs.flyte.org/en/latest/deployment/aws/manual.html#deployment-aws-manual
Also Update the docs as appropriate.
cc : @wild-endeavor

**Comment by evalsocket** [comment]
@sbrunk @wild-endeavor @pmahindrakar-oss this pr is ready. You can review the pr. 

it would be great....if one you guys can test these helm chart, BTW i tested these helm chart on aws

**Comment by EngHabu** [comment]
Do we need ingress to be separate? why is it not part of the flyte-core? It will be no-op if there is no ingress controller is installed... but I think it'll simplify these steps, no?

**Comment by pmahindrakar-oss** [comment]
What should be the plan to complete these . I am not sure if we can go by an assumption that it would work. If there is small sanity check that can be done then that would be good.
```
NOTE: sagemaker, tf_operator, pytorchoperator Is not tested with these workflow....I assume all those plugin will also work
NOTE: Spark workflow is not tested
```

**Comment by sbrunk** [comment]
> @EngHabu As per last time conversation, We decided to separate out ingress controller, but if you want then i can include it in core helm test
> 

@evalsocket I think what @EngHabu means is that we should keep the `Ingress` definition in core, not any controller dependency. If there's no ingress controller, the ingress will just be ignored.

**Comment by EngHabu** [comment]
What @sbrunk said ^

**Pull request closed without merging**
