### PR TITLE
Leverage KubeRay v1 instead of v1alpha1 for resources

### LINKED ISSUE #4802: [BUG] Have option to use v1 instead of v1alpha1 for Ray Jobs
### Describe the bug

Currently Flyte creates Ray Jobs using v1alpha1 instead of v1. Have an option to use v1 instead of v1alpha1 before v1alpha1 deprecation in KubeRay 1.2.0.

Similar to this [issue](https://github.com/flyteorg/flyte/pull/4656), but this now leverages the v1 CRD as an option.

### Expected behavior

Enable users of Flyte to use the later CRD version of Ray jobs provided by KubeRay. These CRDs have more configurations for Ray workloads.

### Additional context to reproduce

_No response_

### Screenshots

_No response_

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

### PR DESCRIPTION
**Pull request by peterghaddad**
## Tracking issue
https://github.com/flyteorg/flyte/issues/4802

Closes #4802

## Why are the changes needed?

The new API version for the Ray Job CRD enables further customization. This will benefit future issues, and will ensure that people are using the latest and greatest API versions. We will still support v1alpha1 and will default to it in the configuration so there are no interruptions to the community.

## What changes were proposed in this pull request?

Add config option to choose between using KubeRay CRD versions.
Add KubeRay v1 as an option for creating KubeRay Jobs.

## How was this patch tested?

Through unit tests.

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] All commits are signed-off.

### CODE REVIEW

**Review by eapolinario — COMMENTED** [review]
Can you add a few tests to `ray_test.go`?

**Comment by peterghaddad** [comment]
@eapolinario I noticed the build failed due to it "being cancelled". Is this expected? Is there a way to test and ensure everything is good to go through the CI? Thanks!

**Comment by eapolinario** [comment]
Thanks for adding tests! I just approved the CI checks (they are setup in such a way that maintainers have to manually approve for them to run).

**Comment by peterghaddad** [comment]
@eapolinario can we try triggering these again? Had to push a couple fixes up.

**Comment by eapolinario** [comment]
@peterghaddad , can you merge master (to get rid of the docs error) and sign DCO? The change itself looks good, but we need fix those before merging.

**Comment by peterghaddad** [comment]
@eapolinario signed off and merged master!

**Review by eapolinario — APPROVED** [review]

**Comment by peterghaddad** [comment]
@eapolinario looks like DCO is still failing. Are we good to merge or will we have to re-write the history?

**Comment by peterghaddad** [comment]
@eapolinario no rush, but politely wanted to follow up on this!

**Pull request merged**
