### PR TITLE
fix: Make Chart compatible to K8s 1.19+

### PR DESCRIPTION
**Pull request by rodrigobaron**
Make use of `contour 5.0.0` and `spark-operator 1.1.15` which uses `v1` deployment API  instead of `v1beta1`.

### CODE REVIEW

**Review by EngHabu — COMMENTED** [review]
Awesome! Thank you for your contribution. Do you mind running `make helm` and committing the changes?

**Comment by rodrigobaron** [comment]
> Awesome! Thank you for your contribution. Do you mind running `make helm` and committing the changes?

done!

**Comment by kumare3** [comment]
Doesn't seem to be your change, but the docs are weirdly broken. Unable to fetch scipy intersphinx

**Comment by rodrigobaron** [comment]
> Doesn't seem to be your change, but the docs are weirdly broken. Unable to fetch scipy intersphinx

seems it moved `scipy` to `scipy-dev` : 
https://docs.scipy.org/doc/scipy/reference/objects.inv [broken]
https://docs.scipy.org/doc/scipy-dev/reference/objects.inv [working]

**Comment by kumare3** [comment]
Interesting must be temporarily broken

**Review by EngHabu — APPROVED** [review]
Approving. docs build error is unrelated..

**Pull request merged**
