### PR TITLE
Update helm/docs per changes in supported task discovery

### PR DESCRIPTION
**Pull request by Sovietaced**
## Why are the changes needed?

These changes aren't strictly needed but they simplify configuration based on the changes introduced in https://github.com/flyteorg/flyte/pull/5460

## What changes were proposed in this pull request?
Removes explicit configuration supported task types since they are now automatically discovered.

## How was this patch tested?

Built and ran the sandbox bundled. Executed a file sensor workflow. 

Screenshot 2024-08-30 at 5 06 03 PM

Seen in the logs..
```
{"json":{"exec_id":"akz742lxljtfn2dk6r7j","node":"n0","ns":"flytesnacks-development","res_ver":"2061","routine":"worker-12","src":"handler.go:180","wf":"flytesnacks:development:sensor.wf"},"level":"info","msg":"Dynamic handler.Handle's called with phase 0.","ts":"2024-08-31T00:03:47Z"}
{"json":{"exec_id":"akz742lxljtfn2dk6r7j","node":"n0","ns":"flytesnacks-development","res_ver":"2061","routine":"worker-12","src":"handler.go:344","tasktype":"sensor","wf":"flytesnacks:development:sensor.wf"},"level":"debug","msg":"Plugin [agent-service] resolved for Handler type [sensor]","ts":"2024-08-31T00:03:47Z"}
```

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] All commits are signed-off.

## Related PRs

[](https://github.com/flyteorg/flyte/pull/5460)

### CODE REVIEW

**Comment by neverett** [comment]
Pinging @davidmirror-ops since he has more expertise in the helm charts & deployment docs than me or Peeter.

**Review by Future-Outlier — COMMENTED** [review]
here's some todo:
1. solve the merged conflict
2. before we merge it, we have to build an image of flyte and test it.
go to this folder and run
make build
https://github.com/flyteorg/flyte/tree/master/docker/sandbox-bundled

if possible, please run a sensor task and provide screenshot that new image works!
https://docs.flyte.org/en/latest/flytesnacks/examples/sensor/file_sensor_example.html

**Comment by Sovietaced** [comment]
> here's some todo:
> 
> 1. solve the merged conflict
> 2. before we merge it, we have to build an image of flyte and test it.
>    go to this folder and run
>    make build
>    https://github.com/flyteorg/flyte/tree/master/docker/sandbox-bundled
> 
> if possible, please run a sensor task and provide screenshot that new image works! https://docs.flyte.org/en/latest/flytesnacks/examples/sensor/file_sensor_example.html

I have updated the PR description and seems that I was able to get the task running, but not sure how to satisfy the sensor so the task completes.

**Comment by Future-Outlier** [comment]
I've built the image and test it.

image

image


image

**Review by Future-Outlier — APPROVED** [review]
LGTM, thank you @Sovietaced

**Pull request merged**
